apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: userk8s
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: userimage
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80