apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      name: employeek8s
      labels:
        app: employee
    spec:
      containers:
        - name: employee-container
          image: employeeimage
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80